allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@typescript/native-preview-darwin-arm64@7.0.0-dev.20260610.1"
  - "@typescript/native-preview-darwin-x64@7.0.0-dev.20260610.1"
  - "@typescript/native-preview-linux-arm64@7.0.0-dev.20260610.1"
  - "@typescript/native-preview-linux-arm@7.0.0-dev.20260610.1"
  - "@typescript/native-preview-linux-x64@7.0.0-dev.20260610.1"
  - "@typescript/native-preview-win32-arm64@7.0.0-dev.20260610.1"
  - "@typescript/native-preview-win32-x64@7.0.0-dev.20260610.1"
  - "@typescript/native-preview@7.0.0-dev.20260610.1"
  - "@oxlint-tsgolint/darwin-arm64@0.24.0"
  - "@oxlint-tsgolint/darwin-x64@0.24.0"
  - "@oxlint-tsgolint/linux-arm64@0.24.0"
  - "@oxlint-tsgolint/linux-x64@0.24.0"
  - "@oxlint-tsgolint/win32-arm64@0.24.0"
  - "@oxlint-tsgolint/win32-x64@0.24.0"
  - "@rspack/binding-darwin-arm64@2.1.2"
  - "@rspack/binding-darwin-x64@2.1.2"
  - "@rspack/binding-linux-arm64-gnu@2.1.2"
  - "@rspack/binding-linux-arm64-musl@2.1.2"
  - "@rspack/binding-linux-riscv64-gnu@2.1.2"
  - "@rspack/binding-linux-riscv64-musl@2.1.2"
  - "@rspack/binding-linux-x64-gnu@2.1.2"
  - "@rspack/binding-linux-x64-musl@2.1.2"
  - "@rspack/binding-wasm32-wasi@2.1.2"
  - "@rspack/binding-win32-arm64-msvc@2.1.2"
  - "@rspack/binding-win32-ia32-msvc@2.1.2"
  - "@rspack/binding-win32-x64-msvc@2.1.2"
  - "@rspack/binding@2.1.2"
  - "@rspack/core@2.1.2"
  - oxlint-tsgolint@0.24.0
