name: Asset Size

on: [pull_request]

jobs:
  compare:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Compare asset sizes
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "./dist/browser/*.js"
          exclude: "{**/*.map,**/node_modules/**}"
